In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Understanding the Raw Data

In [2]:
df = pd.read_csv('../../data/raw/who/WPP2024_Demographic_Indicators_Medium (1).csv.gz', compression='gzip', low_memory=False)
print('--------------------------------------------------------------')
print('Checking values of the table head')
print('--------------------------------------------------------------')
print(df.head())

print()
print('-------------------------------------')
print('File Shape')
print('-------------------------------------')
print(df.shape)

--------------------------------------------------------------
Checking values of the table head
--------------------------------------------------------------
   SortOrder  LocID Notes ISO3_code ISO2_code  SDMX_code  LocTypeID  \
0        NaN   5507   NaN       NaN       NaN        NaN        NaN
1        NaN   5507   NaN       NaN       NaN        NaN        NaN
2        NaN   5507   NaN       NaN       NaN        NaN        NaN
3        NaN   5507   NaN       NaN       NaN        NaN        NaN
4        NaN   5507   NaN       NaN       NaN        NaN        NaN

  LocTypeName  ParentID                           Location  ...  Q0060Male  \
0         NaN       NaN  ADB region: Central and West Asia  ...   654.5798
1         NaN       NaN  ADB region: Central and West Asia  ...   642.5944
2         NaN       NaN  ADB region: Central and West Asia  ...   630.8166
3         NaN       NaN  ADB region: Central and West Asia  ...   619.9937
4         NaN       NaN  ADB region: Central and West Asia  ...   610.3878

  Q0060Female     Q1550  Q1550Male  Q1550Female     Q1560  Q1560Male  \
0    631.8067  297.6529   298.4483     297.2079  443.3215   457.3384
1    619.1788  292.4375   293.1236     292.0887  436.9979   451.4368
2    607.6061  286.6916   287.3395     286.3341  429.8298   444.5151
3    596.2667  281.4671   282.0251     281.1446  423.2008   438.1189
4    586.3428  276.8312   277.5799     276.2557  417.3453   432.7454

   Q1560Female  NetMigrations   CNMR
0     427.3167        201.196  2.907
1     420.7398        195.070  2.760
2     413.5565        182.671  2.529
3     406.9265        164.189  2.222
4     400.7629        163.064  2.157

[5 rows x 67 columns]

-------------------------------------
File Shape
-------------------------------------
(84360, 67)

In [3]:
print('-------------------------------------')
print('Check for Column data Types')
print('-------------------------------------')
print(df.dtypes)
print()
print()
print('--------------------------------------')
print('Check for NULL Values on each column')
print('-------------------------------------')
print(df.isnull().sum())

-------------------------------------
Check for Column data Types
-------------------------------------
SortOrder        float64
LocID              int64
Notes                str
ISO3_code            str
ISO2_code            str
                  ...
Q1560            float64
Q1560Male        float64
Q1560Female      float64
NetMigrations    float64
CNMR             float64
Length: 67, dtype: object


--------------------------------------
Check for NULL Values on each column
-------------------------------------
SortOrder        35568
LocID                0
Notes            72504
ISO3_code        48336
ISO2_code        48488
                 ...
Q1560              555
Q1560Male          555
Q1560Female        555
NetMigrations      555
CNMR               555
Length: 67, dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 84360 entries, 0 to 84359
Data columns (total 67 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SortOrder               48792 non-null  float64
 1   LocID                   84360 non-null  int64
 2   Notes                   11856 non-null  str
 3   ISO3_code               36024 non-null  str
 4   ISO2_code               35872 non-null  str
 5   SDMX_code               43320 non-null  float64
 6   LocTypeID               48792 non-null  float64
 7   LocTypeName             48792 non-null  str
 8   ParentID                48792 non-null  float64
 9   Location                84360 non-null  str
 10  VarID                   84360 non-null  int64
 11  Variant                 84360 non-null  str
 12  Time                    84360 non-null  int64
 13  TPopulation1Jan         84360 non-null  float64
 14  TPopulation1July        83805 non-null  float64
 15  TPopulationMale1July    83805 non-null  float64
 16  TPopulationFemale1July  83805 non-null  float64
 17  PopDensity              83805 non-null  float64
 18  PopSexRatio             83805 non-null  float64
 19  MedianAgePop            83805 non-null  float64
 20  NatChange               83805 non-null  float64
 21  NatChangeRT             83805 non-null  float64
 22  PopChange               83805 non-null  float64
 23  PopGrowthRate           83805 non-null  float64
 24  DoublingTime            49674 non-null  float64
 25  Births                  83805 non-null  float64
 26  Births1519              83805 non-null  float64
 27  CBR                     83805 non-null  float64
 28  TFR                     83805 non-null  float64
 29  NRR                     83805 non-null  float64
 30  MAC                     83805 non-null  float64
 31  SRB                     83805 non-null  float64
 32  Deaths                  83805 non-null  float64
 33  DeathsMale              83805 non-null  float64
 34  DeathsFemale            83805 non-null  float64
 35  CDR                     83805 non-null  float64
 36  LEx                     83805 non-null  float64
 37  LExMale                 83805 non-null  float64
 38  LExFemale               83805 non-null  float64
 39  LE15                    83805 non-null  float64
 40  LE15Male                83805 non-null  float64
 41  LE15Female              83805 non-null  float64
 42  LE65                    83805 non-null  float64
 43  LE65Male                83805 non-null  float64
 44  LE65Female              83805 non-null  float64
 45  LE80                    83805 non-null  float64
 46  LE80Male                83805 non-null  float64
 47  LE80Female              83805 non-null  float64
 48  InfantDeaths            83805 non-null  float64
 49  IMR                     83805 non-null  float64
 50  LBsurvivingAge1         83805 non-null  float64
 51  Under5Deaths            83805 non-null  float64
 52  Q5                      83805 non-null  float64
 53  Q0040                   83805 non-null  float64
 54  Q0040Male               83805 non-null  float64
 55  Q0040Female             83805 non-null  float64
 56  Q0060                   83805 non-null  float64
 57  Q0060Male               83805 non-null  float64
 58  Q0060Female             83805 non-null  float64
 59  Q1550                   83805 non-null  float64
 60  Q1550Male               83805 non-null  float64
 61  Q1550Female             83805 non-null  float64
 62  Q1560                   83805 non-null  float64
 63  Q1560Male               83805 non-null  float64
 64  Q1560Female             83805 non-null  float64
 65  NetMigrations           83805 non-null  float64
 66  CNMR                    83805 non-null  float64
dtypes: float64(58), int64(3), str(6)
memory usage: 46.2 MB

In [5]:

df = df.drop(columns=['Notes','ISO2_code', 'Location', 'LocTypeName', 'Variant', 'NetMigrations'])

In [6]:
df.groupby('ISO3_code').sum()

,SortOrder,LocID,SDMX_code,LocTypeID,ParentID,VarID,Time,TPopulation1Jan,TPopulation1July,TPopulationMale1July,...,Q0060,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,CNMR
ISO3_code,,,,,,,,,,,,,,,,,,,,,
ABW,36936.0,81016,81016.0,608.0,139080.0,304,307876,12700.730,12642.166,6114.453,...,18932.7753,24191.5614,13735.6704,7947.2968,10734.7351,5228.5497,16016.9953,21160.3514,10989.5118,-18.448
AFG,21736.0,608,608.0,608.0,836152.0,304,307876,8374003.026,8304893.268,4185323.496,...,54250.2718,58581.8829,49556.0665,27093.8686,29904.2852,23999.8718,43243.1683,47909.7998,38120.6528,-399.851
AGO,12920.0,3648,3648.0,608.0,138472.0,304,307876,8324703.546,8247139.027,4075470.894,...,56523.7786,63292.2046,49375.2272,27148.3238,32049.4062,22046.1888,43068.2764,50112.4158,35714.1114,62.457
AIA,36632.0,100320,100320.0,608.0,139080.0,304,307876,1674.067,1667.002,807.412,...,18719.1626,23258.0801,14381.0897,7656.7008,9493.6004,5969.3864,15743.4402,19666.2965,12167.2018,-100.967
ALB,32072.0,1216,1216.0,608.0,140600.0,304,307876,344345.494,343139.638,171540.169,...,17926.6661,21237.7618,14522.8124,5736.9722,6894.9477,4561.5229,12025.6682,15034.0631,9004.2111,-593.455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XKX,33288.0,62624,62624.0,608.0,140600.0,304,307876,230527.710,229598.264,114955.251,...,23355.6927,26075.4436,20567.2218,6872.8808,7315.4317,6382.4933,14588.4649,16890.6109,12267.4489,-740.343
YEM,27664.0,134824,134824.0,608.0,140144.0,304,307876,7447324.772,7389943.573,3724980.739,...,43217.7869,48342.3099,37794.7598,17476.6064,20553.3300,14251.4795,31192.3414,36642.6512,25488.8808,-143.166
ZAF,16264.0,107920,107920.0,608.0,138776.0,304,307876,9071828.379,9018163.142,4366770.144,...,49171.7403,57105.4947,41099.9125,25697.6244,30126.4519,21194.6058,42892.6057,50888.2954,34811.0804,341.444
ZMB,12464.0,135888,135888.0,608.0,138320.0,304,307876,4102216.372,4068753.316,2000990.800,...,47072.7882,51907.3633,42272.5923,21942.1021,24260.0812,19666.1747,36307.3238,40724.3047,32014.6074,-154.946
ZWE,12616.0,108832,108832.0,608.0,138320.0,304,307876,2895074.897,2875100.905,1392603.801,...,51751.6204,58367.2697,45319.7035,27426.2678,31319.6859,23680.5864,44507.1984,51021.8104,38283.0820,-498.099

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 84360 entries, 0 to 84359
Data columns (total 61 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SortOrder               48792 non-null  float64
 1   LocID                   84360 non-null  int64
 2   ISO3_code               36024 non-null  str
 3   SDMX_code               43320 non-null  float64
 4   LocTypeID               48792 non-null  float64
 5   ParentID                48792 non-null  float64
 6   VarID                   84360 non-null  int64
 7   Time                    84360 non-null  int64
 8   TPopulation1Jan         84360 non-null  float64
 9   TPopulation1July        83805 non-null  float64
 10  TPopulationMale1July    83805 non-null  float64
 11  TPopulationFemale1July  83805 non-null  float64
 12  PopDensity              83805 non-null  float64
 13  PopSexRatio             83805 non-null  float64
 14  MedianAgePop            83805 non-null  float64
 15  NatChange               83805 non-null  float64
 16  NatChangeRT             83805 non-null  float64
 17  PopChange               83805 non-null  float64
 18  PopGrowthRate           83805 non-null  float64
 19  DoublingTime            49674 non-null  float64
 20  Births                  83805 non-null  float64
 21  Births1519              83805 non-null  float64
 22  CBR                     83805 non-null  float64
 23  TFR                     83805 non-null  float64
 24  NRR                     83805 non-null  float64
 25  MAC                     83805 non-null  float64
 26  SRB                     83805 non-null  float64
 27  Deaths                  83805 non-null  float64
 28  DeathsMale              83805 non-null  float64
 29  DeathsFemale            83805 non-null  float64
 30  CDR                     83805 non-null  float64
 31  LEx                     83805 non-null  float64
 32  LExMale                 83805 non-null  float64
 33  LExFemale               83805 non-null  float64
 34  LE15                    83805 non-null  float64
 35  LE15Male                83805 non-null  float64
 36  LE15Female              83805 non-null  float64
 37  LE65                    83805 non-null  float64
 38  LE65Male                83805 non-null  float64
 39  LE65Female              83805 non-null  float64
 40  LE80                    83805 non-null  float64
 41  LE80Male                83805 non-null  float64
 42  LE80Female              83805 non-null  float64
 43  InfantDeaths            83805 non-null  float64
 44  IMR                     83805 non-null  float64
 45  LBsurvivingAge1         83805 non-null  float64
 46  Under5Deaths            83805 non-null  float64
 47  Q5                      83805 non-null  float64
 48  Q0040                   83805 non-null  float64
 49  Q0040Male               83805 non-null  float64
 50  Q0040Female             83805 non-null  float64
 51  Q0060                   83805 non-null  float64
 52  Q0060Male               83805 non-null  float64
 53  Q0060Female             83805 non-null  float64
 54  Q1550                   83805 non-null  float64
 55  Q1550Male               83805 non-null  float64
 56  Q1550Female             83805 non-null  float64
 57  Q1560                   83805 non-null  float64
 58  Q1560Male               83805 non-null  float64
 59  Q1560Female             83805 non-null  float64
 60  CNMR                    83805 non-null  float64
dtypes: float64(57), int64(3), str(1)
memory usage: 39.4 MB

In [8]:
df = df[df['ISO3_code'].notna()].reset_index(drop=True)

df = df[['ISO3_code', 'Time', 'TPopulation1Jan', 'Births', 'PopGrowthRate', 'InfantDeaths']]

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36024 entries, 0 to 36023
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ISO3_code        36024 non-null  str
 1   Time             36024 non-null  int64
 2   TPopulation1Jan  36024 non-null  float64
 3   Births           35787 non-null  float64
 4   PopGrowthRate    35787 non-null  float64
 5   InfantDeaths     35787 non-null  float64
dtypes: float64(4), int64(1), str(1)
memory usage: 1.8 MB

In [9]:
df.head(80)

   ISO3_code  Time  TPopulation1Jan   Births  PopGrowthRate  InfantDeaths
0        BDI  1950         2229.322  117.211          2.272        17.777
1        BDI  1951         2280.554  118.043          2.185        18.990
2        BDI  1952         2330.938  118.830          2.111        18.923
3        BDI  1953         2380.670  120.089          2.039        18.901
4        BDI  1954         2429.703  121.062          2.028        18.871
..       ...   ...              ...      ...            ...           ...
75       BDI  2025        14220.671  468.720          2.354        16.105
76       BDI  2026        14559.334  471.624          2.306        15.991
77       BDI  2027        14898.980  475.895          2.361        15.932
78       BDI  2028        15254.978  483.052          2.448        15.954
79       BDI  2029        15633.051  491.466          2.312        16.033

[80 rows x 6 columns]

In [10]:
print()
print('-------------------------------------')
print('File Shape')
print('-------------------------------------')
print(df.shape)
print('-------------------------------------')
print('Check for Column data Types')
print('-------------------------------------')
print(df.dtypes)
print()
print()
print('--------------------------------------')
print('Check for NULL Values on each column')
print('-------------------------------------')
print(df.isnull().sum())

-------------------------------------
File Shape
-------------------------------------
(36024, 6)
-------------------------------------
Check for Column data Types
-------------------------------------
ISO3_code              str
Time                 int64
TPopulation1Jan    float64
Births             float64
PopGrowthRate      float64
InfantDeaths       float64
dtype: object


--------------------------------------
Check for NULL Values on each column
-------------------------------------
ISO3_code            0
Time                 0
TPopulation1Jan      0
Births             237
PopGrowthRate      237
InfantDeaths       237
dtype: int64

In [11]:
df.dropna(subset=['PopGrowthRate', 'Births','InfantDeaths' ], how='all', inplace=True)

In [13]:
print()
print('-------------------------------------')
print('File Shape')
print('-------------------------------------')
print(df.head())
print('-------------------------------------')
print('Check for Column data Types')
print('-------------------------------------')
print(df.dtypes)
print()
print()
print('--------------------------------------')
print('Check for NULL Values on each column')
print('-------------------------------------')
print(df.isnull().sum())

-------------------------------------
File Shape
-------------------------------------
  ISO3_code  Time  TPopulation1Jan   Births  PopGrowthRate  InfantDeaths
0       BDI  1950         2229.322  117.211          2.272        17.777
1       BDI  1951         2280.554  118.043          2.185        18.990
2       BDI  1952         2330.938  118.830          2.111        18.923
3       BDI  1953         2380.670  120.089          2.039        18.901
4       BDI  1954         2429.703  121.062          2.028        18.871
-------------------------------------
Check for Column data Types
-------------------------------------
ISO3_code              str
Time                 int64
TPopulation1Jan    float64
Births             float64
PopGrowthRate      float64
InfantDeaths       float64
dtype: object


--------------------------------------
Check for NULL Values on each column
-------------------------------------
ISO3_code          0
Time               0
TPopulation1Jan    0
Births             0
PopGrowthRate      0
InfantDeaths       0
dtype: int64

In [14]:
df = df.rename(columns={'Time': 'YEAR'})

In [16]:
print(df['YEAR'].min(), df['YEAR'].max())

1950 2100

In [17]:
df = df[(df['YEAR'] >= 1994) & (df['YEAR'] <= 2024)].reset_index(drop=True)

In [18]:
df['ISO3_code'].nunique()

237

In [19]:
df['ISO3_code']

0       BDI
1       BDI
2       BDI
3       BDI
4       BDI
       ...
7342    WLF
7343    WLF
7344    WLF
7345    WLF
7346    WLF
Name: ISO3_code, Length: 7347, dtype: str

In [25]:
bcg = pd.read_parquet('../../data/processed/bcg_doses_clean.parquet')
pop_countries = set(df['ISO3_code'].unique())
bcg_countries = set(bcg['CODE'].unique())

only_in_pop = pop_countries - bcg_countries
only_in_bcg = bcg_countries - pop_countries

print(f"Countries in population only: {len(only_in_pop)}")
print(f"Countries in BCG only: {len(only_in_bcg)}")
print(f"Countries in both: {len(pop_countries & bcg_countries)}")

Countries in population only: 65
Countries in BCG only: 0
Countries in both: 172

In [26]:
merged = bcg.merge(
    df.rename(columns={'ISO3_code': 'CODE'}),
    on=['CODE', 'YEAR'],
    how='inner'
)
print(merged.shape)
merged.head()

(3968, 8)

,CODE,NAME,YEAR,DOSES,TPopulation1Jan,Births,PopGrowthRate,InfantDeaths
0,AFG,Afghanistan,2024,1929249,42044.654,1492.956,2.827,63.496
1,ALB,Albania,2024,21780,2801.661,28.283,-0.709,0.202
2,DZA,Algeria,2024,858780,46497.095,881.823,1.355,15.108
3,AGO,Angola,2024,1039799,37312.856,1407.760,3.025,66.926
4,AIA,Anguilla,2024,132,14.523,0.134,1.034,0.001

In [27]:
df.to_parquet('../../data/processed/population_clean.parquet', index=False)
print("Saved to data/processed/population_clean.parquet")

Saved to data/processed/population_clean.parquet